services:
  admin_front:
    container_name: admin_api_${RUN_MODE}
    depends_on:
      - postgres
    build:
      context: ..
      dockerfile: ./apps/admin-api/Dockerfile
    env_file:
      - .env
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}
    restart: on-failure

volumes:
  db: